### ISSUE TITLE
[认领]: 提单工具

### ISSUE THREAD

**Issue by Pylogmon** [deepin-community/coding-quarter#22]
### 任务描述

基于pyside2 和python 开发一款本地提单工具客户端。

此应用涉及内容如下：

- 该应用是禅道提单系统的一个客户端，采用Qt打造的一个PC客户端应用；
- 与禅道系统通过API接口来进行数据交互；--关键接口信息样例，[可点击参考文档](https://github.com/babyfengfjx/coding-quarter/blob/master/2.%E8%BF%9B%E9%98%B6%E9%9A%BE%E5%BA%A6/%E6%8F%90%E5%8D%95%E5%B7%A5%E5%85%B7/%E7%A6%85%E9%81%93API%E6%8E%A5%E5%8F%A3%E4%BF%A1%E6%81%AF.md)，本地可采用搭建mysql数据库方式，来与接口进行数据提交，其他接口可参考上述接口自行定义。
- 客户端应用主要是能提供模板功能，能够让使用者快速复用模板内容进行快速提单；
- 提供草稿功能，能保存多份待提交的bug内容；
- 提供用户提交BUG汇总统计、待处理BUG统计与查看等信息；
- 后期期望能支持提单时根据标题推荐可能存在的问题单信息；
- PyQt来开发客户端前端界面，python编写逻辑功能，后端逻辑功能只需编写基本类和方法体，无需使用真正的后端接口；
- 应用能打包成deb格式，并在deepin上正常安装、卸载；
- 应用界面时尚易用（大致原型可参考下文参考文档部分），界面设计不做要求，以个人审美来决定界面风格。

### 验收标准

- [ ] 有配套的开发文档，包括但不限于：需求分析文档、方案设计文档；
- [ ] 代码逻辑清晰，注释明了，命名规范，具备分而治之、高内聚、低耦合等特点；
- [ ] 应用能按照deepin应用打包规范进行deb格式打包，并能成功安装、卸载；
- [ ] 应用能正常稳定运行，需求功能完整；
- [ ] 应用界面时尚美观易用。

### 联系方式

Email: [pylogmon@outlook.com](mailto://pylogmon@outlook.com)
Github: @Pylogmon

**Comment by Pylogmon** [comment]
后续在此仓库进行开发
[https://github.com/Pylogmon/committer](https://github.com/Pylogmon/committer)

**Comment by Pylogmon** [comment]
@babyfengfjx 基本上做完了，感觉可以验收了😂
Release: [https://github.com/Pylogmon/committer/releases](https://github.com/Pylogmon/committer/releases)
API文档: [https://www.apifox.cn/apidoc/shared-34ee0ef7-be05-459f-ac67-9af2aa4d0165/api-52120533](https://www.apifox.cn/apidoc/shared-34ee0ef7-be05-459f-ac67-9af2aa4d0165/api-52120533)

<table>
<tr>
	<td> <img src=https://user-images.githubusercontent.com/59004461/206690673-9ef80326-b32e-47a5-a4af-f70ffcb14e04.png></img>
	<td> <img src=https://user-images.githubusercontent.com/59004461/206690848-aa7a5518-4875-4621-92b6-ff4f8f45ac27.png></img>
	<td> <img src=https://user-images.githubusercontent.com/59004461/206690881-8757b955-5a87-45f0-8882-ff1a6b205768.png></img>
<tr>
	<td> <img src=https://user-images.githubusercontent.com/59004461/206690924-f34ffdec-367b-463a-b885-94d91092026f.png></img>
	<td> <img src=https://user-images.githubusercontent.com/59004461/206691002-dc2ff219-82b8-40d6-bed2-65e585de77b6.png></img>
</table>

**Comment by BLumia** [comment]
@babyfengfjx 验收已经完成了吗？我看 issue 状态并没有更新。

**Comment by babyfengfjx** [comment]
评定：**合格**

- 项目需求整体完成比较系统，框架内容清晰，还编写了测试服务，前后端实现了独立拉通，界面展示合理；
- 部分细节可以作进一步打磨，环境依赖问题可推进解决。
