### ISSUE TITLE
[认领]: 基于dtk组建开发demo并且输出相关教程

### ISSUE THREAD

**Issue by chenchongbiao** [deepin-community/coding-quarter#28]
### 任务描述

dtk是我们开发的一款开发者工具，但是现阶段虽然存在使用dtk开发的软件：如星火软件商店。但是对于第三方开发者来说dtk的使用门槛还是略高，所以我们需要一些好的demo以及教程文档来帮助开发者入门使用dtk相关模块。设定此任务是需要你了解dtk模块的使用，并且能有一定表述能力，能很好的教会其他人使用dtk模块。

### 验收标准

- [x] demo能正常运行（必须满足）
- [x] 文档语句通顺且无重大逻辑错误（必须满足）
- [x] demo实现的功能具备实用性：如计算器，或者壁纸管理器（加分项）
- [x] 文档教育意义较大（能很好教会新手入门dtk）（加分项）
- [x] 如果能有一份教会大家配置dtk开发环境的文档，那就更好了（加分项）
- [ ] 如果你的demo完成度够高的话，你也可以试试走完打包上架流程，上架深度应用商店，也可以试试打一个玲珑包（需要咨询其他任务导师）（超级加分项，完成此条可以视为完成一个高级难度的任务）

### 联系方式

GitHub：chenchongbiao
邮箱：[379865549@qq.com](379865549@qq.com)
Matrix：bluesky

**Comment by xzl01** [comment]
项目：https://github.com/chenchongbiao/manager

**Comment by xzl01** [comment]
评定：优秀

**Comment by xzl01** [comment]
评语：此项目完成度很高，首先功能设计和界面设计非常合理，同dtk期望的风格一致，同时在开发过程中，能够发现dtk中存在的一些问题，而且能帮助dtk完善相关文档以及提出建议。其次其功能具备实用性，对于使用deepin进行开发的入门开发者是很友好的。美中不足的是，还未进行打包，期望可以完成debian打包和尝试玲珑打包，并且上架商店，以让更多的用户接触，使用和反馈。
