### ISSUE TITLE
[认领]: xdg功能的完善

### ISSUE THREAD

**Issue by BladeYW** [deepin-community/coding-quarter#33]
### 任务描述

**任务描述**
完善 xdg-desktop-portal-dde 的screenshot,Wallpaper接口。

关于screenshot的完整如[xdg-desktop-portal关于screenshot](https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-org.freedesktop.impl.portal.Screenshot)描述。具体效果可以尝试在kde或者gnome上使用flameshot等截图工具(然而flameshot等通用截图工具现在一般在wayland下才使用xdp)，如果截图工具实现了这类高级功能的话，gnome和kde会给出弹窗让你选择截图的内容。

关于Wallpaper接口内容内容在[xdp Wallpaper](https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-org.freedesktop.impl.portal.Wallpaper)可以找到，需要了解的接口有dde-daemon org.deepin.daemon.Appearance的 SetMonitorBackground方法。（然而v20上的xdg-desktop-portal并没有wallpaper的接口，所以你可能需要在v23或者其他发行版的dde桌面环境进行调试，或者可以选择自己编译新的xdg-desktop-portal）

仓库位于 [xdg-desktop-portal-dde](https://github.com/linuxdeepin/xdg-desktop-portal-dde)

要求：

项目使用CMake管理

**环境准备**
需要准备装有dde桌面环境的发行版，kwin后端

调试工具可以选择 [ashpd-demo](https://github.com/bilelmoussaoui/ashpd),可能需要flatpak环境

基本的开发工具包括qt5-base,cmake等。

环境配置过程如下

sudo cp misc/dde.portal /usr/share/xdg-desktop-portal/portals/

cmake -B build
cmake --build build

./build/src/xdg-desktop-protal-dde
接下来可以使用ashpd-demo调用截图功能进行调试，(然而这个demo只能截全图，也许之后会自己实现一个完整的demo进行测试)

### 验收标准

最终程序实现下述功能中其一:

 可以实现xdp中完整的截图功能，例如弹窗选择窗口
 可以通过xdp设置桌面背景

### 联系方式

github: BladeYW
Email: yuwei.zou@uq.net.au

**Comment by Decodetalkers** [comment]
你现在可以接手任务吗。需要对Dbus有了解呢

**Comment by BladeYW** [comment]
你好，实在抱歉，之前本来打算接手这个任务的，但了解了一段时间以后发现有点低估任务难度了，水平还不够。加上前段时间阳得比较厉害，躺了很久，所以停了很久没有更新任务状态。我已经把这个issue给关闭了，实在不好意思。

From: Access ***@***.***>
Date: Monday, 30 January 2023 at 2:37 pm
To: deepin-community/coding-quarter ***@***.***>
Cc: Yuwei Zou ***@***.***>, Author ***@***.***>
Subject: Re: [deepin-community/coding-quarter] [认领]: xdg功能的完善 (Issue #33)

你现在可以接手任务吗。需要对Dbus有了解呢

―
