### ISSUE TITLE
[认领]: DTK文档标准化

### ISSUE THREAD

**Issue by MoLuoPro** [deepin-community/coding-quarter#36]
### 任务描述

dtkcore等dtk模块一直因为文档而诟病，其实这么好的模块它是拥有文档的，但是文档并不符合我们认为的可维护标准，所以我们需要做一件事：在代码内部有且仅有英文注释存在，在代码外部的doc文件夹中书写符合doxygen标准的文档。所以你需要将代码中的中文注释移动到doc文件夹下，最好能够添加英文注释。

### 验收标准

- [ ] 能提供准确的文档注释（必须满足）
- [ ]  文档修改被合并（必须满足）
- [ ]  在修改文档时发现并修正现有文档中的错误或者其他问题（加分项）
- [ ]  添加或更新文档使用示例（加分项）

### 联系方式

GitHub：moluopro  
邮箱：2056673609@qq.com  
Matrix：moluopro

**Comment by qq909244296** [comment]
我想认领，请问我改如何做？

**Comment by xzl01** [comment]
> 我想认领，请问我改如何做？

提出一个新的issue进行认领

**Comment by xzl01** [comment]
评定：不合格
