### ISSUE TITLE
[认领]: [找BUG]Qt-Bug查找

### ISSUE THREAD

**Issue by 878547387** [deepin-community/coding-quarter#37]
### 任务描述

使用deepin v20系统上提供Qt5、Qt6基础环境，参考https://bugreports.qt.io/ 或 https://forum.qt.io/ 查找Qt bug，基于QtCreator编写demo在deepin上测试系统提供Qt5、Qt6是否存在Qt bug（官方未修复），如果存在提交发现Qt bug与复现demo。

### 验收标准

验收标准
[ ] Bug 真实有效，且Qt上游最新代码中还未修复（必须满足）
[ ] 可以根据复现步骤和demo复现问题

根据反馈问题严重程度与复现demo评估任务完成程度

### 联系方式

github:878547387
Email:878547387@qq.com

**Comment by BLumia** [comment]
问下，这个任务的完成状况大概是怎样呢？如果已经完成的话，可以联系对接人更新任务状态哈

**Comment by BLumia** [comment]
暂且标记为认领人放弃。如果与实际情况不符，请及时联系我更新任务状态。感谢！
