### ISSUE TITLE
[认领]: [DDE移植]维护deepin-overlay(1-3)

### ISSUE THREAD

**Issue by OriPoin** [deepin-community/coding-quarter#44]
### 任务描述

DDE 是深度桌面环境的简称， 基于 Qt 开发，目前主要在 Deepin 操作系统中使用，也可以在其他 Linux 发行版中使用。
目前 deepin-overlay 上已经打包了 DDE 的组件，但是存在版本无法即时得到更新， 缺少部分组件， 适配不完整存在 bug 等问题。
目前已经完整适配的架构有 amd64 / riscv 部分适配 loong 架构

本次任务的目标是将 DDE 的组件完好移植到 deepin-overlay 上， 能够顺畅使用:
1. 需要升级过时的 DDE 软件包
2. 需要打包缺少的部分组件
3. 需要修复 deepin-overlay 存在的 bug, 整理/编写 patch

目前 DDE 在其他发行版也有移植，比如 Arch, openSUSE, Fedora 等, 可以参考这些发行版的移植工作。处理 bug 时可以看看其他发行版是否已有修复方案。

### 验收标准

- 软件常规升级/维护/新增打包/Patch整理被 deepin-overlay/main-tree 仓库接受
- 自己编写的 Patch 可以被验证解决了特定问题

### 联系方式

Github: @OriPoin
mailto:oripoin@outlook.com
Telegram: https://t.me/oripoin

**Comment by RevySR** [comment]
未完成 无相关可见进度
